/**
 * core/state — package root docs live in core/state.js (the facade).
 */

/* Action creators — the only shape-correct way to produce dispatch
 * payloads. Thin by design: validation lives in the reducer, which treats
 * every payload (even ones forged through dispatch) as hostile. */

export const actions = {
  navigate: (view, params) => ({ type: 'NAVIGATE', view, params }),
  bootComplete: (library) => ({ type: 'BOOT_COMPLETE', library }),
  updateSettings: (patch) => ({ type: 'SETTINGS_UPDATE', patch }),
  updatePrayerSettings: (patch) => ({ type: 'SETTINGS_UPDATE_PRAYER', patch }),
  setAlertTriggerStatus: (status) => ({ type: 'ALERT_TRIGGER_STATUS', status }),
  toggleFavorite: (itemId) => ({ type: 'FAVORITE_TOGGLE', itemId }),
  createCollection: (id, name) => ({ type: 'COLLECTION_CREATE', id, name }),
  deleteCollection: (id) => ({ type: 'COLLECTION_DELETE', id }),
  renameCollection: (id, name) => ({ type: 'COLLECTION_RENAME', id, name }),
  addToCollection: (collectionId, itemId) => ({
    type: 'COLLECTION_ADD_ITEM',
    collectionId,
    itemId,
  }),
  removeFromCollection: (collectionId, itemId) => ({
    type: 'COLLECTION_REMOVE_ITEM',
    collectionId,
    itemId,
  }),
  setCounter: (itemId, patch, target) => ({ type: 'COUNTER_SET', itemId, patch, target }),
  resetCounter: (itemId, target) => ({ type: 'COUNTER_RESET', itemId, target }),
  addReminder: (reminder) => ({ type: 'REMINDER_ADD', reminder }),
  updateReminder: (id, patch) => ({ type: 'REMINDER_UPDATE', id, patch }),
  deleteReminder: (id) => ({ type: 'REMINDER_DELETE', id }),
  addCalendarNote: (note) => ({ type: 'CALENDAR_NOTE_ADD', note }),
  updateCalendarNote: (id, patch) => ({ type: 'CALENDAR_NOTE_UPDATE', id, patch }),
  deleteCalendarNote: (id) => ({ type: 'CALENDAR_NOTE_DELETE', id }),
  recordStatistic: (itemId, categoryId, count, newSession) => ({
    type: 'STATISTICS_RECORD',
    itemId,
    categoryId,
    count,
    newSession,
  }),
  addReadingSeconds: (seconds) => ({ type: 'READING_ADD_SECONDS', seconds }),
  pushHistory: (itemId, categoryId) => ({ type: 'HISTORY_PUSH', itemId, categoryId }),
  addSearchHistory: (query) => ({ type: 'SEARCH_HISTORY_ADD', query }),
  clearSearchHistory: () => ({ type: 'SEARCH_HISTORY_CLEAR' }),
  upsertCustomLibrary: (library) => ({ type: 'CUSTOM_LIBRARY_UPSERT', library }),
  deleteCustomLibrary: (libraryId) => ({ type: 'CUSTOM_LIBRARY_DELETE', libraryId }),
  setTasbihActive: (itemId, phrase) => ({ type: 'TASBIH_SET_ACTIVE', itemId, phrase }),
  setSpeakingItem: (itemId) => ({ type: 'SPEECH_SET_ACTIVE', itemId }),
  setLibraryIndex: (itemIndex) => ({ type: 'LIBRARY_SET_INDEX', itemIndex }),
  contentManageToggle: () => ({ type: 'CONTENT_MANAGE_TOGGLE' }),
  restoreState: (payload) => ({ type: 'RESTORE_STATE', payload }),
  resetAll: () => ({ type: 'RESET_ALL' }),
  setQuranMeta: (meta) => ({ type: 'QURAN_META_LOADED', meta }),
  setLoadError: (key, failed) => ({ type: 'LOAD_ERROR_SET', key, failed }),
  retryDataLoad: (key) => ({ type: 'DATA_LOAD_RETRY', key }),
  setQuranSurah: (number, surah) => ({ type: 'QURAN_SURAH_LOADED', number: String(number), surah }),
  setQuranSurahsBulk: (docs) => ({ type: 'QURAN_SURAHS_BULK_LOADED', docs }),
  // (v5.2.0) Translation-compare: second-edition overlay text per surah.
  setQuranTranslationBDoc: (number, doc) => ({
    type: 'QURAN_TRANSLATION_B_LOADED',
    number: String(number),
    doc,
  }),
  setQuranBookmark: (surah) => ({ type: 'QURAN_BOOKMARK_SET', surah }),
  setMushafMeta: (meta) => ({ type: 'MUSHAF_META_LOADED', meta }),
  setMushafPage: (page, doc) => ({ type: 'MUSHAF_PAGE_LOADED', page: String(page), doc }),
  setMushafBookmark: (page) => ({ type: 'MUSHAF_BOOKMARK_SET', page }),
  // (v4.4) TRUE fullscreen Mushaf — see reducer MUSHAF_FULLSCREEN_SET.
  setMushafFullscreen: (on) => ({ type: 'MUSHAF_FULLSCREEN_SET', on: on === true }),
  // (v4.5) Classic-reader immersive mode — see reducer READER_IMMERSIVE_SET.
  setReaderImmersive: (on) => ({ type: 'READER_IMMERSIVE_SET', on: on === true }),
  setQuranWords: (number, words) => ({ type: 'QURAN_WORDS_LOADED', number: String(number), words }),
  setQuranRoots: (roots) => ({ type: 'QURAN_ROOTS_LOADED', roots }),
  setQuranRootsFull: (roots) => ({ type: 'QURAN_ROOTS_FULL_LOADED', roots }),
  setTafsirEditions: (editions) => ({ type: 'TAFSIR_EDITIONS_LOADED', editions }),
  setTafsirText: (editionId, number, text) => ({
    type: 'TAFSIR_TEXT_LOADED',
    editionId,
    number: String(number),
    text,
  }),
  openWordStudy: (surah, ayah, i) => ({
    type: 'WORD_STUDY_OPEN',
    surah: String(surah),
    ayah: String(ayah),
    i: Number(i),
  }),
  closeWordStudy: () => ({ type: 'WORD_STUDY_CLOSE' }),
  setTajweedPool: (pool) => ({ type: 'TAJWEED_POOL_LOADED', pool }),
  setHadithIndex: (index) => ({ type: 'HADITH_INDEX_LOADED', index }),
  hadithIndexFailed: () => ({ type: 'HADITH_INDEX_FAILED' }),
  setHadithBook: (bookId, doc) => ({ type: 'HADITH_BOOK_LOADED', bookId, doc }),
  hadithBookFailed: (bookId) => ({ type: 'HADITH_BOOK_FAILED', bookId }),
  setHadithDaily: (daily) => ({ type: 'HADITH_DAILY_SET', daily }),
  setHadithView: (patch) => ({ type: 'HADITH_VIEW_SET', patch }),
  // (v5.2.0) Hadith bookmarks — key is "<bookId>:<n>".
  toggleHadithBookmark: (bookId, n) => ({
    type: 'HADITH_BOOKMARK_TOGGLE',
    key: `${String(bookId)}:${String(n)}`,
  }),
  // Personal hadith notes — empty/blank text deletes the note.
  setHadithNote: (key, text) => ({ type: 'HADITH_NOTE_SET', key, text }),
  // Recitation queues (playlists) of { surah, from, to } ranges.
  createPlaylist: (id, name) => ({ type: 'PLAYLIST_CREATE', id, name }),
  renamePlaylist: (id, name) => ({ type: 'PLAYLIST_RENAME', id, name }),
  deletePlaylist: (id) => ({ type: 'PLAYLIST_DELETE', id }),
  addPlaylistItem: (id, item) => ({ type: 'PLAYLIST_ADD_ITEM', id, item }),
  removePlaylistItem: (id, index) => ({ type: 'PLAYLIST_REMOVE_ITEM', id, index }),
  setSurahPlayback: (patch) => ({ type: 'SURAH_PLAYBACK_SET', patch }),
  // Hifz (memorization, v3.17)
  hifzSessionStart: ({ surah, level }) => ({ type: 'HIFZ_SESSION_START', surah, level }),
  hifzSessionEnd: () => ({ type: 'HIFZ_SESSION_END' }),
  hifzLevel: (level) => ({ type: 'HIFZ_LEVEL', level }),
  hifzReveal: ({ ayah, word = null }) => ({ type: 'HIFZ_REVEAL', ayah, word }),
  hifzRehide: () => ({ type: 'HIFZ_REHIDE' }),
  hifzMarkMemorized: ({ surah }) => ({ type: 'HIFZ_MARK_MEMORIZED', surah }),
  hifzReview: ({ surah, grade }) => ({ type: 'HIFZ_REVIEW', surah, grade }),
  // Voluntary fasting prefs (v3.18) — the fasts themselves reuse the
  // generic RAMADAN_FAST_TOGGLE on non-Ramadan month keys (shared log).
  fastingToggleCategory: (cat) => ({ type: 'FASTING_TOGGLE_CATEGORY', cat }),
  fastingToggleRemind: (cat) => ({ type: 'FASTING_TOGGLE_REMIND', cat }),
  fastingSetRemindTime: (time) => ({ type: 'FASTING_SET_REMIND_TIME', time }),
  // Quick-log sadaqah (v3.19)
  logSadaqah: (note = '') => ({ type: 'SADAQAH_LOG', note }),
  removeSadaqah: (id) => ({ type: 'SADAQAH_REMOVE', id }),
  // (v4.4) Sunnah prayer tracker
  toggleSunnah: (id) => ({ type: 'SUNNAH_TOGGLE', id }),
  // (v4.4) Qada' (make-up) tracker
  qadaAdd: (prayer, n, reason = 'other', date = '') => ({
    type: 'QADA_ADD',
    prayer,
    n,
    reason,
    date,
  }),
  qadaComplete: (prayer) => ({ type: 'QADA_COMPLETE', prayer }),
  qadaRemoveAll: (prayer) => ({ type: 'QADA_REMOVE_ALL', prayer }),
  // (v4.4) Location profiles
  saveLocationProfile: (name, id = null) => ({ type: 'LOCATION_PROFILE_SAVE', name, id }),
  applyLocationProfile: (id) => ({ type: 'LOCATION_PROFILE_APPLY', id }),
  removeLocationProfile: (id) => ({ type: 'LOCATION_PROFILE_REMOVE', id }),
  // (v4.4) Dua journal + reflections
  addDua: (text) => ({ type: 'DUA_JOURNAL_ADD', text }),
  toggleDuaAnswered: (id) => ({ type: 'DUA_JOURNAL_TOGGLE_ANSWERED', id }),
  removeDua: (id) => ({ type: 'DUA_JOURNAL_REMOVE', id }),
  addReflection: (text, week, promptId) => ({
    type: 'REFLECTION_ADD',
    text,
    week,
    promptId,
  }),
  removeReflection: (id) => ({ type: 'REFLECTION_REMOVE', id }),
  // (v4.4) Ramadan planner (taraweeh / i'tikaf / last-ten checklist)
  ramadanPlannerToggle: (slice, key, day) => ({
    type: 'RAMADAN_PLANNER_TOGGLE',
    slice,
    key,
    day,
  }),
  // (v4.4) Multi-profile hifz
  switchHifzProfile: (id) => ({ type: 'HIFZ_PROFILE_SWITCH', id }),
  // (v4.4) Mutashabihat drill session (ephemeral)
  updateMutashabihat: (patch) => ({ type: 'MUTASHABIHAT_SESSION_UPDATE', patch }),
  // (v4.4) Reader immersion (ephemeral)
  toggleImmersiveReader: () => ({ type: 'IMMERSIVE_READER_TOGGLE' }),
  // (v4.4) Plan import (family sharing, zero-account)
  importPlan: (plan) => ({ type: 'PLAN_IMPORT', plan }),
  markNudgeShown: () => ({ type: 'NUDGE_SHOWN' }),
  dismissNudge: () => ({ type: 'NUDGE_DISMISS' }),
  // Data health (v3.26)
  markBackupExported: () => ({ type: 'BACKUP_EXPORTED' }),
  setDataHealthStorage: (value) => ({ type: 'DATA_HEALTH_STORAGE', value }),
  setDataHealthDryRun: (value) => ({ type: 'DATA_HEALTH_DRYRUN', value }),
  recordTajweedPracticeResult: (ruleId, perfect) => ({
    type: 'TAJWEED_PRACTICE_RESULT',
    ruleId,
    perfect,
  }),
  updateMushafPrefs: (patch) => ({ type: 'SETTINGS_UPDATE_MUSHAF_PREFS', patch }),
  toggleAyahBookmark: (key, surah, ayah, page) => ({
    type: 'AYAH_BOOKMARK_TOGGLE',
    key,
    surah,
    ayah,
    page,
  }),
  updateAyahBookmark: (key, patch) => ({ type: 'AYAH_BOOKMARK_UPDATE', key, patch }),
  createBookmarkFolder: (id, name) => ({ type: 'BOOKMARK_FOLDER_CREATE', id, name }),
  renameBookmarkFolder: (id, name) => ({ type: 'BOOKMARK_FOLDER_RENAME', id, name }),
  deleteBookmarkFolder: (id) => ({ type: 'BOOKMARK_FOLDER_DELETE', id }),
  removeAyahBookmark: (key) => ({ type: 'AYAH_BOOKMARK_REMOVE', key }),
  markMushafPageVisited: (page) => ({ type: 'MUSHAF_PAGE_VISITED', page: String(page) }),
  resetMushafProgress: () => ({ type: 'MUSHAF_PROGRESS_RESET' }),
  setKhatmaPlan: (plan) => ({ type: 'KHATMA_PLAN_SET', plan }),
  clearKhatmaPlan: () => ({ type: 'KHATMA_PLAN_CLEAR' }),
  toggleRamadanFast: (logKey, day) => ({ type: 'RAMADAN_FAST_TOGGLE', logKey, day: String(day) }),
  setZakatPrefs: (patch) => ({ type: 'ZAKAT_PREFS_SET', patch }),
  setZakatInput: (field, value) => ({ type: 'ZAKAT_INPUT_SET', field, value }),
  clearZakatInputs: () => ({ type: 'ZAKAT_INPUTS_CLEAR' }),
  saveZakatSnapshot: (snapshot) => ({ type: 'ZAKAT_SNAPSHOT_SAVE', snapshot }),
  deleteZakatSnapshot: (id) => ({ type: 'ZAKAT_SNAPSHOT_DELETE', id }),
  updateZakatSnapshot: (id, patch) => ({ type: 'ZAKAT_SNAPSHOT_UPDATE', id, patch }),
  pruneDanglingRefs: (validIds) => ({ type: 'PRUNE_DANGLING_REFS', validIds }),
  setAudioPlayer: (patch) => ({ type: 'AUDIO_SET_PLAYER', patch }),
  setAudioPrefs: (patch) => ({ type: 'AUDIO_SET_PREFS', patch }),
  addCustomReciter: (entry) => ({ type: 'AUDIO_CUSTOM_ADD', entry }),
  removeCustomReciter: (id) => ({ type: 'AUDIO_CUSTOM_REMOVE', id }),
  markAudioDownload: (key, bytes, remove) => ({ type: 'AUDIO_DOWNLOAD_DONE', key, bytes, remove }),
  markAudioDownloadStart: (key) => ({ type: 'AUDIO_DOWNLOAD_START', key }),
  markAudioDownloadEnd: (key) => ({ type: 'AUDIO_DOWNLOAD_END', key }),
  setAudioManagerQuery: (query) => ({ type: 'AUDIO_MANAGER_QUERY', query }),
  // (v4.2) batch download lifecycle: flips the Download All button to Stop.
  setAudioBatchRunning: (running) => ({ type: 'AUDIO_BATCH_RUNNING', running }),
  setAudioCatalogReady: () => ({ type: 'AUDIO_CATALOG_READY' }),
  setRecitingAyah: (key) => ({ type: 'RECITATION_SET_ACTIVE', key }),
  toggleChecklistItem: (item, date) => ({ type: 'CHECKLIST_TOGGLE', item, date }),
  // (v4.6.0) "Clear today's checklist" — the sheet affordance. Deletes the
  // day entry entirely so the checkbox rows all render unchecked.
  resetChecklistDay: (date) => ({ type: 'CHECKLIST_DAY_RESET', date }),
  cyclePrayerLog: (item) => ({ type: 'PRAYER_LOG_CYCLE', item }),
  startQuiz: (deck) => ({ type: 'QUIZ_START', deck }),
  answerQuiz: (itemId) => ({ type: 'QUIZ_ANSWER', itemId }),
  nextQuiz: () => ({ type: 'QUIZ_NEXT' }),
  exitQuiz: () => ({ type: 'QUIZ_EXIT' }),
  shiftStatsHeatmapMonth: (delta, baseRef) => ({
    type: 'STATS_HEATMAP_MONTH_SHIFT',
    delta,
    baseRef,
  }),
  dismissOnboarding: () => ({ type: 'ONBOARDING_DISMISS' }),
  installPromptReady: () => ({ type: 'INSTALL_PROMPT_READY' }),
  installPromptClear: () => ({ type: 'INSTALL_PROMPT_CLEAR' }),
  markAppInstalled: () => ({ type: 'INSTALL_DONE' }),
};
